---
title: Site
timezone: Europe/Samara
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Some posts about IT
baseurl: 
url: 
twitter_username: ram0973
github_username: ram0973
theme: minima
plugins:
- jekyll-feed
