---
title: Linux Java and others
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ram0973@gmail.com
description: Linux Java and others
baseurl: ''
url: ''
github_username: ram0973
theme: minima
plugins:
- jekyll-feed
